package com.test.persistence.beans;

public class TCmmOrgInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CORP_ORG_ID
     *
     * @mbggenerated
     */
    private String corpOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CORP_ORG_NM
     *
     * @mbggenerated
     */
    private String corpOrgNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CORP_ORG_SNM
     *
     * @mbggenerated
     */
    private String corpOrgSnm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CORP_ORG_TYP
     *
     * @mbggenerated
     */
    private String corpOrgTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CRE_OPR_ID
     *
     * @mbggenerated
     */
    private String creOprId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CRE_DT
     *
     * @mbggenerated
     */
    private String creDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.CRE_TM
     *
     * @mbggenerated
     */
    private String creTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.UPD_OPR_ID
     *
     * @mbggenerated
     */
    private String updOprId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.UPD_DT
     *
     * @mbggenerated
     */
    private String updDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.UPD_TM
     *
     * @mbggenerated
     */
    private String updTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMM_ORG_INF.TM_SMP
     *
     * @mbggenerated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CORP_ORG_ID
     *
     * @return the value of T_CMM_ORG_INF.CORP_ORG_ID
     *
     * @mbggenerated
     */
    public String getCorpOrgId() {
        return corpOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CORP_ORG_ID
     *
     * @param corpOrgId the value for T_CMM_ORG_INF.CORP_ORG_ID
     *
     * @mbggenerated
     */
    public void setCorpOrgId(String corpOrgId) {
        this.corpOrgId = corpOrgId == null ? null : corpOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CORP_ORG_NM
     *
     * @return the value of T_CMM_ORG_INF.CORP_ORG_NM
     *
     * @mbggenerated
     */
    public String getCorpOrgNm() {
        return corpOrgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CORP_ORG_NM
     *
     * @param corpOrgNm the value for T_CMM_ORG_INF.CORP_ORG_NM
     *
     * @mbggenerated
     */
    public void setCorpOrgNm(String corpOrgNm) {
        this.corpOrgNm = corpOrgNm == null ? null : corpOrgNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CORP_ORG_SNM
     *
     * @return the value of T_CMM_ORG_INF.CORP_ORG_SNM
     *
     * @mbggenerated
     */
    public String getCorpOrgSnm() {
        return corpOrgSnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CORP_ORG_SNM
     *
     * @param corpOrgSnm the value for T_CMM_ORG_INF.CORP_ORG_SNM
     *
     * @mbggenerated
     */
    public void setCorpOrgSnm(String corpOrgSnm) {
        this.corpOrgSnm = corpOrgSnm == null ? null : corpOrgSnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CORP_ORG_TYP
     *
     * @return the value of T_CMM_ORG_INF.CORP_ORG_TYP
     *
     * @mbggenerated
     */
    public String getCorpOrgTyp() {
        return corpOrgTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CORP_ORG_TYP
     *
     * @param corpOrgTyp the value for T_CMM_ORG_INF.CORP_ORG_TYP
     *
     * @mbggenerated
     */
    public void setCorpOrgTyp(String corpOrgTyp) {
        this.corpOrgTyp = corpOrgTyp == null ? null : corpOrgTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CRE_OPR_ID
     *
     * @return the value of T_CMM_ORG_INF.CRE_OPR_ID
     *
     * @mbggenerated
     */
    public String getCreOprId() {
        return creOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CRE_OPR_ID
     *
     * @param creOprId the value for T_CMM_ORG_INF.CRE_OPR_ID
     *
     * @mbggenerated
     */
    public void setCreOprId(String creOprId) {
        this.creOprId = creOprId == null ? null : creOprId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CRE_DT
     *
     * @return the value of T_CMM_ORG_INF.CRE_DT
     *
     * @mbggenerated
     */
    public String getCreDt() {
        return creDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CRE_DT
     *
     * @param creDt the value for T_CMM_ORG_INF.CRE_DT
     *
     * @mbggenerated
     */
    public void setCreDt(String creDt) {
        this.creDt = creDt == null ? null : creDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.CRE_TM
     *
     * @return the value of T_CMM_ORG_INF.CRE_TM
     *
     * @mbggenerated
     */
    public String getCreTm() {
        return creTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.CRE_TM
     *
     * @param creTm the value for T_CMM_ORG_INF.CRE_TM
     *
     * @mbggenerated
     */
    public void setCreTm(String creTm) {
        this.creTm = creTm == null ? null : creTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.UPD_OPR_ID
     *
     * @return the value of T_CMM_ORG_INF.UPD_OPR_ID
     *
     * @mbggenerated
     */
    public String getUpdOprId() {
        return updOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.UPD_OPR_ID
     *
     * @param updOprId the value for T_CMM_ORG_INF.UPD_OPR_ID
     *
     * @mbggenerated
     */
    public void setUpdOprId(String updOprId) {
        this.updOprId = updOprId == null ? null : updOprId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.UPD_DT
     *
     * @return the value of T_CMM_ORG_INF.UPD_DT
     *
     * @mbggenerated
     */
    public String getUpdDt() {
        return updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.UPD_DT
     *
     * @param updDt the value for T_CMM_ORG_INF.UPD_DT
     *
     * @mbggenerated
     */
    public void setUpdDt(String updDt) {
        this.updDt = updDt == null ? null : updDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.UPD_TM
     *
     * @return the value of T_CMM_ORG_INF.UPD_TM
     *
     * @mbggenerated
     */
    public String getUpdTm() {
        return updTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.UPD_TM
     *
     * @param updTm the value for T_CMM_ORG_INF.UPD_TM
     *
     * @mbggenerated
     */
    public void setUpdTm(String updTm) {
        this.updTm = updTm == null ? null : updTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMM_ORG_INF.TM_SMP
     *
     * @return the value of T_CMM_ORG_INF.TM_SMP
     *
     * @mbggenerated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMM_ORG_INF.TM_SMP
     *
     * @param tmSmp the value for T_CMM_ORG_INF.TM_SMP
     *
     * @mbggenerated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}