package com.test.persistence.mappers;

import com.test.persistence.beans.TCmmOrgInf;

public interface TCmmOrgInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String corpOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    int insert(TCmmOrgInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    int insertSelective(TCmmOrgInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    TCmmOrgInf selectByPrimaryKey(String corpOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCmmOrgInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMM_ORG_INF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCmmOrgInf record);
}